spring.application.name=json-auth-service

# Neon PostgreSQL
spring.datasource.url=${DB_URL_AUTH}
spring.datasource.username=${DB_USER_AUTH}
spring.datasource.password=${DB_PASS_AUTH}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=${JWT_SECRET}

# Production port
server.port=8082

# Actuator Monitoring
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.tags.service=${spring.application.name}
management.metrics.distribution.slo.http.server.requests=10ms,50ms,100ms,200ms,500ms,1s,2s,5s